### PR TITLE
NXP-22758: Add Hungarian language

### PR DESCRIPTION
**Pull request by sguitter**

### CODE REVIEW

**Comment by atchertchian** [comment]
:+1: is it the pristine English version?

**Comment by sguitter** [comment]
It's a copy from src/main/resources/crowdin/messages.properties.

**Comment by atchertchian** [comment]
:+1: don't hesitate to say it in the commit message next time

**Comment by atchertchian** [comment]
merged with defefc281f170b78fd91ce87380e50d091a4baf1

**Pull request closed without merging**
